"use client"
import Sidebar from "@/components/Sidebar";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<>
			<Sidebar />
			{children}
		</>
	);
}
