import dynamic from "next/dynamic";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import "./nprogress.css";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const TopProgressBar = dynamic(() => import("@/components/TopProgressBar"), {
	ssr: false,
});

export default function RootLayout({ children }) {

	return (
		<html lang="en">
			<body>
				<TopProgressBar />
				<Navbar />
				{children}
			</body>
		</html>
	);
}
